image: docker:git
services:
  - docker:dind

variables:
  ROS_DISTRO: "foxy"
  DOCKER_TLS_CERTDIR: "/certs"
  TMPDIR: "${CI_PROJECT_DIR}.tmp" #
  CCACHE_DIR: ${CI_PROJECT_DIR}/ccache
  PARALLEL_BUILDS: 1

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - ccache

before_script:
  - cat /etc/resolv.conf
  - echo 'nameserver 8.8.8.8' >> /etc/resolv.conf
  - cat /etc/resolv.conf
  - ping 8.8.8.8 -c 3
  - apk update
  - apk add --update bash coreutils tar
  - apk add --no-cache --upgrade grep
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci -b master --single-branch

.foxy:
  tags:
    - docker
  script:
    - .industrial_ci/gitlab.sh
  variables:
    ROS_DISTRO: "foxy"
    VERBOSE_OUTPUT: "true"
    VERBOSE_TESTS: "true"
    NOT_TEST_BUILD: "true"
    NOT_TEST_DOWNSTREAM: "true"

foxy:build:
  extends: .foxy
  stage: build
  needs: []
