image: docker:stable-git
services:
  - docker:19.03.14-dind

variables:
  ROS_DISTRO: "foxy"
  DOCKER_TLS_CERTDIR: "/certs"
  TMPDIR: "${CI_PROJECT_DIR}.tmp" #
  PARALLEL_BUILDS: 1

before_script:
#  - apk update
#  - apk add bash coreutils tar
#  - apk add --no-cache --upgrade grep
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci -b master --single-branch

.foxy:
  tags:
    - docker
  script:
    #- .industrial_ci/gitlab.sh
    - pwd
    - ls -l
    #- sleep 60
    - cd /var/lib/docker/volumes/runner-wh1uep-a-project-1999-concurrent-0-cache-c33bcaa1fd2c77edfc3893b41966cea8/_data/agrob/vineslam_stack/vineslam
    - .industrial_ci/gitlab.sh
  variables:
    ROS_DISTRO: "foxy"
    VERBOSE_OUTPUT: "true"
    VERBOSE_TESTS: "true"
    NOT_TEST_BUILD: "true"
    NOT_TEST_DOWNSTREAM: "true"

foxy:build:
  extends: .foxy
  stage: build
  needs: []
