slam_node:
  world_frame_id: map_nn2

  use_semantic_features: False
  use_lidar_features: True
  use_vertical_planes: True
  use_imu: False
  use_gyroscope: False
  use_gps: True
  use_gps_altitude: False

  lightweight_version: False

  lidar_sensor_frame: velodyne
  camera_sensor_frame: camera_frame

  save_logs: False
  logs_folder: "/home/andresaguiar/Documents/vineslam_logs/"

  camera_info:
    baseline: 0.12 # meters
    fx: 692.95849609375  # pixels
    cx: 692.95849609375  # pixels
    horizontal_fov: 1.413 # radians
    vertical_fov: 1.200 # radians
    image_width: 1280 # px
    image_height: 720 # px

  robot_dimensions:
    x: 1.00 # meters
    y: 0.68 # meters
    z: 0.90 # meters

  multilayer_mapping:
    # Datum
    datum:
      latitude: 41.2055059
      longitude: -8.3074066
      altitude: 248.00900000000001

    # Satellite occupancy grid map datum
    satellite_datum:
      latitude: 41.2057809184083
      longitude: -8.30806732177734

    # Topological map definitions
    topological_map:
      input_file: "/home/andresaguiar/ROS/catkin_ws_ros1/src/agrob_pp/agrob_topologic/agrob_topologic_graph/data/topological_map.xml"

    # Grid map definitions
    grid_map:
      origin:
        x: -200.0
        y: -50.0
        z: -7.5
      width: 400.0
      lenght: 150.0
      height: 15.0
      resolution: 0.25 # meters
      output_folder: "/home/andresaguiar/Desktop/"

  pf:
    n_particles: 500

    # Particles innovation
    sigma_xx: 0.5 # meters
    sigma_yy: 0.5 # meters
    sigma_zz: 0.3 # meters
    sigma_RR: 0.3 # radians
    sigma_PP: 0.3 # radians
    sigma_YY: 1.5 # radians