slam_node:
  robot_model: rocha  # {agrob, rocha}
  lidar_sensor: livox  # {velodyne, livox, ...}
  world_frame_id: map_nn2
  use_semantic_features: False
  use_lidar_features: True
  use_image_features: False
  use_gps: False
  use_imu: True

  lidar_sensor_frame: livox_frame
  camera_sensor_frame: zed_camera_left_optical_frame

  camera_info:
    baseline: 0.12 # meters
    fx: 692.95849609375  # pixels
    cx: 692.95849609375  # pixels

  robot_dimensions:
    x: 1.00 # meters
    y: 0.68 # meters
    z: 0.90 # meters

  multilayer_mapping:
    # Datum
    datum:
      latitude: 41.16666452664269
      longitude: -7.5550953842432085
      altitude: 294.75472108864517

    # Grid map definitions
    grid_map:
      origin:
        x: -110.0
        y: -110.0
        z: -18.0
      width: 220.0
      lenght: 220.0
      height: 25.0
      resolution: 0.25 # meters
      output_folder: "/home/andresaguiar/Desktop/"

  pf:
    n_particles: 500

    # Particles innovation
    sigma_xx: 0.5 # meters
    sigma_yy: 0.5 # meters
    sigma_zz: 0.3 # meters
    sigma_RR: 0.3 # radians
    sigma_PP: 0.3 # radians
    sigma_YY: 0.7 # radians