localization_node:
  world_frame_id: map_nn2

  use_semantic_features: True
  use_lidar_features: True
  use_vertical_planes: True
  use_imu: False
  use_gyroscope: False
  use_gps: True
  use_gps_altitude: True

  lightweight_version: True

  lidar_sensor_frame: velodyne
  camera_sensor_frame: zed_camera_left_optical_frame

  # Robot initial guess position in polar coordinates
  robot:
    latitude: 41.16666452664269
    longitude: -7.5550953842432085
    altitude: 294.75472108864517

  camera_info:
    baseline: 0.12 # meters
    fx: 692.95849609375  # pixels
    cx: 692.95849609375  # pixels
    horizontal_fov: 1.413 # radians
    vertical_fov: 1.200 # radians
    image_width: 1280 # px
    image_height: 720 # px

  robot_dimensions:
    x: 1.00 # meters
    y: 0.68 # meters
    z: 0.90 # meters


  multilayer_mapping:
    # Grid map definitions
    grid_map:
      map_file_path: "/home/andresaguiar/Documents/maps/VineSLAM/map_aveleda_27_05_2021/map_1622207539.xml"
      elevation_map_file_path: "/home/andresaguiar/Documents/maps/VineSLAM/map_aveleda_27_05_2021/elevation_map_1622207539.xml"
      output_folder: "/home/andresaguiar/Desktop/"

  pf:
    n_particles: 500

    # Particles innovation
    sigma_xx: 0.5 # meters
    sigma_yy: 0.5 # meters
    sigma_zz: 0.3 # meters
    sigma_RR: 0.3 # radians
    sigma_PP: 0.3 # radians
    sigma_YY: 0.1 # radians
