dense_mapping_node:
  world_frame_id: map_nn2
  logs_folder: "/home/andresaguiar/Documents/vineslam_logs/seixo-03-2021/"

  lidar_sensor_frame: velodyne

  multilayer_mapping:
    # Datum
    datum:
      latitude: 41.2055204
      longitude: -8.307482
      altitude: 255.632

    # Grid map definitions
    grid_map:
      # map_file_path: "/home/andresaguiar/Desktop/map_1625657085.xml"
      map_file_path: "/home/andresaguiar/Documents/maps/VineSLAM/map_seixo_12_07_2021/map_1626116457.xml"
      origin:
        x: -110.0
        y: -110.0
        z: -18.0
      width: 220.0
      lenght: 220.0
      height: 25.0
      resolution: 0.25 # meters
      output_folder: "/home/andresaguiar/Desktop/"