# File where major input definitions and values are set
---
# Camera calibration info
camera_info:
  baseline: 0.12       # meters
  delta_d: 1.0         # stereo matcher disparity error in pixels
  h_fov: 85            # ZED's horizontal field of view in degrees
  cam_pitch: 11.3      # camera inclination in degrees
  cam_height: 1.0      # camera height in meters
  img_width: 1280      # pixels
  img_height: 720      # pixels
  fx: 692.95849609375  # pixels
  fy: 636.41424560546  # pixels
  cx: 692.95849609375  # pixels
  cy: 382.80633544921  # pixels

# Feature extractor and descriptor settings
# - supported types: SURF, SIFT
image_feature:
  type: "SURF"

# Grid map definitions
# - origin of the grid map
# - map width and height
# - resolution of each cell (area = resolution x resolution)
grid_map:
  origin:
    x: -10
    y: -20
  width: 50
  height: 50
  resolution: 0.10 # meters
  metric: "descriptor"

# 3D map definitions
map_3D:
  max_range: 5.0 # meters
  max_height: 1.2 # meters

# ICP scan matching parameters
# - maximum number of iterations
# - error derivative threshold
# - minimum distance (euclidean or L2-norm for descriptor) to consider
#   a correspondence an inlier
ICP:
  max_iters: 10
  tolerance: 0.0001
  distance_threshold: 0.08

# Particle filter:
# - s constants - sample_motion_model_odometry from Probabilistic Robotics
# - standard deviation of zero mean gaussians for non observable states (z, roll, pitch)
# - particles2D - number of particles for landmark-based particle filter
# - particles3D - number of particles for feature-based particle filter
pf:
  srr: 0.2 # rotation - rotation
  srt: 0.5 # rotation - translation
  str: 0.2 # translation - rotation
  stt: 0.5 # translation - translation
  sigma_z: 0.2 # meters
  sigma_roll: 5.0 # degrees
  sigma_pitch: 5.0 # degrees
  n_particles2D: 0
  n_particles3D: 30
...
