# File where major input definitions and values are provided
---
# Camera calibration info
camera_info:
  baseline: 0.12       # meters
  delta_d: 1.0         # stereo matcher disparity error in pixels
  h_fov: 85            # ZED's horizontal field of view in degrees
  cam_pitch: 11.3      # camera inclination in degrees
  cam_height: 1.0      # camera height in meters
  img_width: 1280      # pixels
  img_height: 720      # pixels
  fx: 692.95849609375  # pixels
  fy: 636.41424560546  # pixels
  cx: 692.95849609375  # pixels
  cy: 382.80633544921  # pixels

# Grid map definitions
# - origin of the grid map
# - map width and height
# - resolution of each cell (area = resolution x resolution)
grid_map:
  origin:
    x: -10
    y: -10
  width: 50
  height: 20
  resolution: 0.25 # meters

# Particle filter constants to perform inovation and number of particles
# std_trans = trans * alpha_trans
# std_rot   = rot * alpha_rot
pf:
  n_particles: 2000 # number of particles
  alpha_trans: 0.5
  alpha_rot:   0.5
...
