# File where major input definitions and values are set
---
# General system settings
system:
  num_threads: 4 # (1 or 4) if you do not want multithreading, just set this to 1
  publish_odom: True # if true, vineslam publishes its localization also in a odometry msg
  use_gps: True
  gps_datum:
    lat: 41.205517 # initial gps latitude
    long: -8.3073515 # initial gps longiture
    head: 0. # initial gps heading (yaw - radians)

# Camera calibration info
camera_info:
  baseline: 0.12       # meters
  delta_d: 1.0         # stereo matcher disparity error in pixels
  h_fov: 85            # ZED's horizontal field of view in degrees
  cam_pitch: 11.3      # camera inclination in degrees
  cam_height: 0.95     # camera height in meters
  depth_hfov: 90.0     # degrees - depth image horizontal field of view
  depth_vfov: 60.0     # degrees - depth image vertical field of view
  img_width: 1280      # pixels
  img_height: 720      # pixels
  fx: 692.95849609375  # pixels
  fy: 636.41424560546  # pixels
  cx: 692.95849609375  # pixels
  cy: 382.80633544921  # pixels

# Feature extractor and descriptor settings
# - supported types: SURF
image_feature:
  type: "SURF"

# 3D cloud feature extraction settings
cloud_feature:
  downsample_factor: 10  # constant to downscale dense disparity image
  ground_theta: 2.0  # (degrees) vertical angle threshold to consider ground points
  # from "Fast Range Image-Based Segmentation of Sparse 3D Laser Scans for Online Operation"
  planes_theta: 5.0 # (degrees) angle threshold to cluster planes
  RANSAC:
    max_iters: 20  # maximum number of RANSAC iterations
    dist_threshold: 0.08  # inliers distance threshold
  edge_threshold: 0.05 # curvature maximum threshold to consider a feature as an adge


# Grid map definitions
# - origin of the grid map
# - map width and height
# - resolution of each cell (area = resolution x resolution)
grid_map:
  origin:
    x: -75
    y: -25
  width: 150
  height: 50
  resolution: 0.25 # meters
  metric: "descriptor"
  save_map: True
  output_file: "/home/andre-criis/map.xml"
  input_file: "/home/andre-criis/map.xml"


# 3D map definitions
map_3D:
  max_range: 5.0 # meters
  max_height: 1.2 # meters
  correspondence_threshold: 0.05 # meters

# 2D semantic map definition
map_semantic:
  stdev_threshold: 0.2 # (meters) filtering threshold
  filter_frequency: 5 # number of iterations between filtering calls


# ICP scan matching parameters
# - maximum number of iterations
# - error derivative threshold
# - minimum distance (euclidean or L2-norm for descriptor) to consider
#   a correspondence an inlier
# - boolean to choose whether or not we want to reject outliers
ICP:
  max_iters: 20
  tolerance: 0.0001
  distance_threshold: 0.08
  reject_outliers: "True"


# Particle filter:
pf:
  n_particles: 500 # number of particles

  ## --- PARTICLES INOVATION -- #
  srr: 0.005 # rotation - rotation (rad / rad)
  srt: 0.01 # rotation - translation (rad / meter)
  str: 0.008 # translation - rotation (meter / rad)
  stt: 0.2 # translation - translation (meter / meter)
  sigma_xy: 0.15 # meters (just for initialization)
  sigma_z: 0.01 # meters
  sigma_roll: 2.5 # degrees
  sigma_pitch: 2.5 # degrees
  sigma_yaw: 1.0 # degrees (just for initialization)

  ## -- Weights calculation -- #
  ## This is a multi-modal weight calculation
  ## To normalize the weight of each modality, the sum of all of them is maximum 1
  ## --> Inter-normalization
  semantic_norm: 0.4
  corners_norm: 0.2
  ground_norm: 0.4
  gps_norm: 0.4
  ## --> Intra-normalization (standard deviations of each gaussian)
  sigma_ground_z: 0.08 # meters (derivative)
  sigma_ground_rp: 1.0 # degrees
  sigma_landmark_matching: 0.1 # meters
  sigma_feature_matching: 0.4 # meters
  sigma_corner_matching: 0.1 # meters
  sigma_gps: 0.2 # meters
...
