# File where major input definitions and values are set
---
# General system settings
system:
  # - Define system inputs
  use_ground_plane: True
  use_landmarks: True
  use_corners: True
  use_icp: True
  use_gps: False
  # ---------------------
  gps_datum:
    lat: 41.205517 # initial gps latitude (larger)
    long: -8.3073515 # initial gps longiture (larger)
  # ---------------------

# Camera calibration info
camera_info:
  baseline: 0.12       # meters
  depth_hfov: 90.0     # degrees - depth image horizontal field of view
  depth_vfov: 60.0     # degrees - depth image vertical field of view
  img_width: 1280      # pixels
  img_height: 720      # pixels
  fx: 692.95849609375  # pixels
  fy: 636.41424560546  # pixels
  cx: 692.95849609375  # pixels
  cy: 382.80633544921  # pixels


multilayer_mapping:
  # Grid map definitions
  grid_map:
    origin:
      x: -75
      y: -25
    width: 150
    height: 50
    resolution: 0.25 # meters
    metric: "euclidean"
    save_map: True
    output_folder: "/home/andre-criis/Source/vineslam_data/08-2020-paper-clusters/raw_data/maps/"
    input_file: "/home/andre-criis/map.xml"
  # Feature extractor and descriptor settings
  image_feature:
    hessian_threshold: 3500 # SURF threshold: the higher the value, the lesser the number of features computed
  # 3D cloud feature extraction settings
  cloud_feature:
    downsample_factor: 10  # constant to downscale dense disparity image
  # 3D map definitions
  map_3D:
    max_range: 5.0 # meters
    max_height: 2.0 # meters
  # ICP definitions
  ICP:
    max_iters: 20
    distance_threshold: 0.02
    reject_outliers: True


pf:
  n_particles: 500

  srr: 0.005 # rotation - rotation (rad / rad)
  srt: 0.010 # rotation - translation (rad / meter)
  str: 0.008 # translation - rotation (meter / rad)
  stt: 0.150 # translation - translation (meter / meter)

  sigma_xy: 0.15 # meters (just for initialization)
  sigma_yaw: 1.0 # degrees (just for initialization)
  sigma_z: 0.008 # meters
  sigma_roll: 1.0 # degrees
  sigma_pitch: 1.0 # degrees

  ## --- PARTICLES UPDATE -- #
  sigma_landmark_matching: 0.01 # meters
  sigma_feature_matching: 0.05 # meters
  sigma_corner_matching: 0.005 # meters
  sigma_ground_rp: 1.0 # degrees
  sigma_gps: 0.08 # meters

  k_clusters: 5
...
